# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/app.json
Variables:
  com:
    axonivy:
      demo:
        anonymous:
          baseUrl: http://localhost/anonymous-demos/pro
